services:
  - type: web
    runtime: node
    name: sangeet-supabase-server
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
