services:
  - type: web
    runtime: node
    name: sangeet-supabase-server
<<<<<<< HEAD
    rootDir: server
=======
    rootDir: .
>>>>>>> origin/main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
