-- =============================================
-- Soulful Bhakti - Additional Tables
-- Based on Spotify Clone architecture
-- =============================================

-- User profiles (extends auth.users)
CREATE TABLE IF NOT EXISTS public.user_profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name TEXT,
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own profile" ON public.user_profiles
    FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.user_profiles
    FOR UPDATE USING (auth.uid() = id);

-- Liked songs
CREATE TABLE IF NOT EXISTS public.liked_songs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    track_id UUID NOT NULL REFERENCES public.tracks(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    UNIQUE(user_id, track_id)
);

ALTER TABLE public.liked_songs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own likes" ON public.liked_songs
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own likes" ON public.liked_songs
    FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own likes" ON public.liked_songs
    FOR DELETE USING (auth.uid() = user_id);

-- Playlists
CREATE TABLE IF NOT EXISTS public.playlists (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    cover_image TEXT,
    visibility TEXT DEFAULT 'public' CHECK (visibility IN ('public', 'unlisted', 'private')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

ALTER TABLE public.playlists ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view public playlists" ON public.playlists
    FOR SELECT USING (visibility = 'public' OR auth.uid() = user_id);
CREATE POLICY "Users can insert own playlists" ON public.playlists
    FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own playlists" ON public.playlists
    FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own playlists" ON public.playlists
    FOR DELETE USING (auth.uid() = user_id);

-- Playlist songs (many-to-many with ordering)
CREATE TABLE IF NOT EXISTS public.playlist_songs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playlist_id UUID NOT NULL REFERENCES public.playlists(id) ON DELETE CASCADE,
    track_id UUID NOT NULL REFERENCES public.tracks(id) ON DELETE CASCADE,
    position INTEGER NOT NULL DEFAULT 0,
    added_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    UNIQUE(playlist_id, track_id)
);

ALTER TABLE public.playlist_songs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view playlist songs" ON public.playlist_songs
    FOR SELECT USING (
        EXISTS (SELECT 1 FROM public.playlists WHERE id = playlist_id AND (visibility = 'public' OR user_id = auth.uid()))
    );
CREATE POLICY "Owners can manage playlist songs" ON public.playlist_songs
    FOR INSERT WITH CHECK (
        EXISTS (SELECT 1 FROM public.playlists WHERE id = playlist_id AND user_id = auth.uid())
    );
CREATE POLICY "Owners can update playlist songs" ON public.playlist_songs
    FOR UPDATE USING (
        EXISTS (SELECT 1 FROM public.playlists WHERE id = playlist_id AND user_id = auth.uid())
    );
CREATE POLICY "Owners can delete playlist songs" ON public.playlist_songs
    FOR DELETE USING (
        EXISTS (SELECT 1 FROM public.playlists WHERE id = playlist_id AND user_id = auth.uid())
    );

-- Song play tracking (for popular/recommended)
CREATE TABLE IF NOT EXISTS public.song_plays (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_id UUID NOT NULL REFERENCES public.tracks(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

ALTER TABLE public.song_plays ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view play counts" ON public.song_plays
    FOR SELECT USING (true);
CREATE POLICY "Authenticated users can insert plays" ON public.song_plays
    FOR INSERT WITH CHECK (auth.uid() = user_id);
